# Default configuration file for repo-scan
# This file is installed to /etc/repo-scan/config.yaml

# General settings
debug: false
verbose: false
workspace_dir: "/var/tmp/repo-scan"
max_workers: 4
scan_timeout: 3600  # 1 hour

# Scanner configurations
scanners:
  semgrep:
    enabled: true
    timeout: 300
    memory_limit: "1g"
    cpu_limit: "1.0"
    custom_rules: null
    exclude_patterns: []
    include_patterns: []
  
  gitleaks:
    enabled: true
    timeout: 300
    memory_limit: "512m"
    cpu_limit: "1.0"
    custom_config: null
    exclude_patterns: []
    include_patterns: []
  
  trivy:
    enabled: true
    timeout: 300
    memory_limit: "1g"
    cpu_limit: "1.0"
    custom_config: null
    exclude_patterns: []
    include_patterns: []
  
  bandit:
    enabled: true
    timeout: 300
    memory_limit: "512m"
    cpu_limit: "1.0"
    custom_config: null
    exclude_patterns: []
    include_patterns: []
  
  checkov:
    enabled: true
    timeout: 300
    memory_limit: "1g"
    cpu_limit: "1.0"
    custom_config: null
    exclude_patterns: []
    include_patterns: []

# Notification settings
notifications:
  slack_webhook: null
  slack_channel: null
  email_smtp_server: null
  email_smtp_port: 587
  email_username: null
  email_password: null
  email_from: null
  email_to: []

# Database settings
database:
  url: "sqlite:///var/lib/repo-scan/repo_scan.db"
  echo: false
  pool_size: 5
  max_overflow: 10

# API server settings
api:
  host: "127.0.0.1"
  port: 8000
  workers: 1
  reload: false
  auth_enabled: false
  jwt_secret: null
  oidc_provider: null
  oidc_client_id: null
  oidc_client_secret: null

# Security settings
verify_gpg_signatures: true
allowed_git_protocols: ["https", "ssh"]

# Risk scoring configuration
risk_scoring:
  severity_weights:
    LOW: 10
    MEDIUM: 40
    HIGH: 75
    CRITICAL: 100
  
  multipliers:
    history_exposure: 1.25
    private_key: 2.0
    api_token: 1.8
    published_exploit: 1.5
    production_branch: 1.3
    world_writable: 1.2
    high_confidence: 1.1
    low_confidence: 0.8
  
  max_findings_for_score: 20
